### ISSUE TITLE
почему не использовать std::function<void()> ?

### ISSUE THREAD

**Issue by Yertugan** [ZhalgasFromMSU/async_server#1]
https://github.com/ZhalgasFromMSU/async_server/blob/f39646c965b3cbb24783b85dfd1053c0b2dece06/include/util/task.hpp#L8

**Comment by ZhalgasFromMSU** [comment]
std::function [работает](https://en.cppreference.com/w/cpp/utility/functional/function) только с копируемыми типами

> Class template std::function is a general-purpose polymorphic function wrapper. Instances of std::function can store, copy, and invoke any [CopyConstructible](https://en.cppreference.com/w/cpp/named_req/CopyConstructible) [Callable](https://en.cppreference.com/w/cpp/named_req/Callable) target

поэтому, например, такой код не скомпилируется:
```
std::function<void()> foo() {
    std::unique_ptr<int> ptr{new int(1)};
    return [ptr = std::move(ptr)] {
        std::cerr << *ptr;
        return;
    };
}
```

Плюс, скорее всего, выполнение виртуальной функции на тред пуле даст большую производительность, чем лишняя аллокация в std::function
